"""Framework-independent core domain for EEA."""

from eea_core.dependency_graph import (
    ChangeObservation,
    DependencyImpact,
    DependencyNodeRef,
    DependencyNodeState,
    EngineeringDependencyEdge,
    ImpactPlan,
    ImpactPlanStep,
    canonical_semantic_hash,
)
from eea_core.domain_extensions import (
    DomainActivation,
    DomainCompositionPlan,
    DomainDescriptor,
    DomainIREnvelope,
    DomainIRRef,
)
from eea_core.protocol import (
    ProtocolDefinition,
    ProtocolField,
    ProtocolGenerationBundle,
    ProtocolIR,
    ProtocolMessage,
    ProtocolTransport,
)
from eea_core.review import ReviewStatus
from eea_core.testing import (
    AutomationLevel,
    RequirementTestSnapshot,
    TestCase,
    TestCaseResult,
    TestExecutionStatus,
    TestIR,
    TestResultAuthority,
    TestRun,
    TestType,
)

__all__ = [
    "AutomationLevel",
    "ChangeObservation",
    "DependencyImpact",
    "DependencyNodeRef",
    "DependencyNodeState",
    "DomainActivation",
    "DomainCompositionPlan",
    "DomainDescriptor",
    "DomainIREnvelope",
    "DomainIRRef",
    "ProtocolDefinition",
    "ProtocolField",
    "ProtocolGenerationBundle",
    "ProtocolIR",
    "ProtocolMessage",
    "ProtocolTransport",
    "RequirementTestSnapshot",
    "ReviewStatus",
    "TestCase",
    "TestCaseResult",
    "TestExecutionStatus",
    "TestIR",
    "TestResultAuthority",
    "TestRun",
    "TestType",
]

from eea_core.entities import (
    Artifact,
    EngineeringDecision,
    EntityBase,
    Evidence,
    Issue,
    Job,
    PermissionAuditRecord,
    Project,
    TraceabilityEdge,
)
from eea_core.enums import (
    ArtifactStatus,
    DecisionStatus,
    DependencyKind,
    DependencyNodeStatus,
    EngineeringErrorCode,
    EvidenceType,
    ImpactAction,
    InvalidationPolicy,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    RequirementFieldStatus,
    RequirementPriority,
    RequirementStatus,
    RequirementType,
    RequirementValueType,
    TraceabilityRelation,
)
from eea_core.reliability import (
    OutboxEvent,
    OutboxEventStatus,
    ProcessedEvent,
    SideEffectJournal,
    SideEffectStatus,
    canonical_json,
    payload_sha256,
    stable_event_key,
)

__all__ = [
    "Artifact",
    "ArtifactStatus",
    "DecisionStatus",
    "DependencyKind",
    "DependencyNodeStatus",
    "EngineeringDecision",
    "EngineeringDependencyEdge",
    "EngineeringErrorCode",
    "EntityBase",
    "Evidence",
    "EvidenceType",
    "ImpactAction",
    "ImpactPlan",
    "ImpactPlanStep",
    "InvalidationPolicy",
    "Issue",
    "IssueSeverity",
    "IssueStatus",
    "Job",
    "JobStatus",
    "OutboxEvent",
    "OutboxEventStatus",
    "Permission",
    "PermissionAuditRecord",
    "ProcessedEvent",
    "Project",
    "ProjectStatus",
    "RequirementFieldStatus",
    "RequirementPriority",
    "RequirementStatus",
    "RequirementType",
    "RequirementValueType",
    "SideEffectJournal",
    "SideEffectStatus",
    "TraceabilityEdge",
    "TraceabilityRelation",
    "canonical_json",
    "canonical_semantic_hash",
    "payload_sha256",
    "stable_event_key",
]
