"""Framework-independent core domain for EEA."""

from eea_core.domain_extensions import (
    DomainActivation,
    DomainCompositionPlan,
    DomainDescriptor,
    DomainIREnvelope,
    DomainIRRef,
)
from eea_core.protocol import (
    ProtocolDefinition,
    ProtocolField,
    ProtocolGenerationBundle,
    ProtocolIR,
    ProtocolMessage,
    ProtocolTransport,
)
from eea_core.review import ReviewStatus
from eea_core.testing import (
    AutomationLevel,
    RequirementTestSnapshot,
    TestCase,
    TestCaseResult,
    TestExecutionStatus,
    TestIR,
    TestResultAuthority,
    TestRun,
    TestType,
)

__all__ = [
    "AutomationLevel",
    "DomainActivation",
    "DomainCompositionPlan",
    "DomainDescriptor",
    "DomainIREnvelope",
    "DomainIRRef",
    "ProtocolDefinition",
    "ProtocolField",
    "ProtocolGenerationBundle",
    "ProtocolIR",
    "ProtocolMessage",
    "ProtocolTransport",
    "RequirementTestSnapshot",
    "ReviewStatus",
    "TestCase",
    "TestCaseResult",
    "TestExecutionStatus",
    "TestIR",
    "TestResultAuthority",
    "TestRun",
    "TestType",
]

from eea_core.entities import (
    Artifact,
    EngineeringDecision,
    EntityBase,
    Evidence,
    Issue,
    Job,
    PermissionAuditRecord,
    Project,
    TraceabilityEdge,
)
from eea_core.enums import (
    ArtifactStatus,
    DecisionStatus,
    EngineeringErrorCode,
    EvidenceType,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    RequirementFieldStatus,
    RequirementPriority,
    RequirementStatus,
    RequirementType,
    RequirementValueType,
    TraceabilityRelation,
)

__all__ = [
    "Artifact",
    "ArtifactStatus",
    "DecisionStatus",
    "EngineeringDecision",
    "EngineeringErrorCode",
    "EntityBase",
    "Evidence",
    "EvidenceType",
    "Issue",
    "IssueSeverity",
    "IssueStatus",
    "Job",
    "JobStatus",
    "Permission",
    "PermissionAuditRecord",
    "Project",
    "ProjectStatus",
    "RequirementFieldStatus",
    "RequirementPriority",
    "RequirementStatus",
    "RequirementType",
    "RequirementValueType",
    "TraceabilityEdge",
    "TraceabilityRelation",
]
