"""Canonical Core enums shared by storage, API, and generated clients."""

from enum import StrEnum


class ProjectStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class RequirementType(StrEnum):
    FUNCTIONAL = "FUNCTIONAL"
    PERFORMANCE = "PERFORMANCE"
    INTERFACE = "INTERFACE"
    SAFETY = "SAFETY"
    CONSTRAINT = "CONSTRAINT"
    UNKNOWN = "UNKNOWN"


class RequirementPriority(StrEnum):
    MUST = "MUST"
    SHOULD = "SHOULD"
    COULD = "COULD"
    UNKNOWN = "UNKNOWN"


class RequirementStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    INCOMPLETE = "INCOMPLETE"
    AMBIGUOUS = "AMBIGUOUS"
    COMPLETE = "COMPLETE"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class RequirementValueType(StrEnum):
    TEXT = "TEXT"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    ENUM = "ENUM"
    ENGINEERING_VALUE = "ENGINEERING_VALUE"
    OBJECT = "OBJECT"
    LIST = "LIST"


class RequirementFieldStatus(StrEnum):
    PRESENT = "PRESENT"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"
    AMBIGUOUS = "AMBIGUOUS"


class ArtifactStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    INVALID = "INVALID"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"


class BuildStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    BLOCKED = "BLOCKED"


class StaticAnalysisStatus(StrEnum):
    """Lifecycle of one deterministic static-analysis execution."""

    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    BLOCKED = "BLOCKED"


class DomainActivationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    INCOMPATIBLE = "INCOMPATIBLE"
    BLOCKED = "BLOCKED"


class DomainTrustTier(StrEnum):
    BUNDLED = "bundled"
    SIGNED_TRUSTED = "signed_trusted"
    COMMUNITY_UNTRUSTED = "community_untrusted"


class DomainRulePhase(StrEnum):
    PRE_SCHEMA = "PRE_SCHEMA"
    PRE_DESIGN = "PRE_DESIGN"
    PRE_GENERATION = "PRE_GENERATION"
    POST_GENERATION = "POST_GENERATION"
    PRE_EXECUTION = "PRE_EXECUTION"
    POST_EXECUTION = "POST_EXECUTION"
    RELEASE_GATE = "RELEASE_GATE"


class BuildProfile(StrEnum):
    HOST_SMOKE = "HOST_SMOKE"
    DEVICE = "DEVICE"


class ComponentAuthority(StrEnum):
    VENDOR_OFFICIAL = "VENDOR_OFFICIAL"
    UPSTREAM_OFFICIAL = "UPSTREAM_OFFICIAL"
    EEA_CURATED = "EEA_CURATED"
    PROJECT_LOCAL = "PROJECT_LOCAL"
    REFERENCE_ONLY = "REFERENCE_ONLY"


class ComponentSourceType(StrEnum):
    CMSIS_PACK = "CMSIS_PACK"
    VENDOR_SDK = "VENDOR_SDK"
    GIT = "GIT"
    ARCHIVE = "ARCHIVE"
    LOCAL_PROJECT = "LOCAL_PROJECT"
    PLATFORMIO = "PLATFORMIO"
    CURATED = "CURATED"


class SoftwareComponentRole(StrEnum):
    MCU_SDK = "MCU_SDK"
    CMSIS_CORE = "CMSIS_CORE"
    CMSIS_DEVICE = "CMSIS_DEVICE"
    HAL = "HAL"
    LL = "LL"
    RTOS = "RTOS"
    DSP = "DSP"
    MIDDLEWARE = "MIDDLEWARE"
    BSP = "BSP"
    LIBRARY = "LIBRARY"
    REFERENCE = "REFERENCE"


class ComponentRevisionKind(StrEnum):
    GIT_COMMIT = "GIT_COMMIT"
    PACK_HASH = "PACK_HASH"
    ARCHIVE_HASH = "ARCHIVE_HASH"
    CONTENT_HASH = "CONTENT_HASH"
    IMMUTABLE_ID = "IMMUTABLE_ID"


class DependencyLockStatus(StrEnum):
    DRAFT = "DRAFT"
    LOCKED = "LOCKED"
    STALE = "STALE"
    INVALID = "INVALID"


class ComponentMaterializationStatus(StrEnum):
    PENDING = "PENDING"
    MATERIALIZED = "MATERIALIZED"
    HASH_MISMATCH = "HASH_MISMATCH"
    FAILED = "FAILED"


class EvidenceType(StrEnum):
    DOCUMENT = "DOCUMENT"
    DEVICE_DB = "DEVICE_DB"
    REPOSITORY = "REPOSITORY"
    RULE = "RULE"
    TOOL = "TOOL"
    SIMULATION = "SIMULATION"
    HARDWARE_TEST = "HARDWARE_TEST"
    USER_CONFIRMATION = "USER_CONFIRMATION"
    IMPORTED_PROJECT = "IMPORTED_PROJECT"


class IssueSeverity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IssueStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class DecisionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"


class JobStatus(StrEnum):
    """FIX-08 canonical Job state machine."""

    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    BLOCKED_PERMISSION = "BLOCKED_PERMISSION"
    BLOCKED_RESOURCE = "BLOCKED_RESOURCE"
    RECOVERING = "RECOVERING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    FAILED_NEEDS_RECONCILE = "FAILED_NEEDS_RECONCILE"
    CANCELLED = "CANCELLED"


class Permission(StrEnum):
    """FIX-08 canonical permission catalog."""

    READ = "READ"
    WRITE = "WRITE"
    BUILD = "BUILD"
    NETWORK = "NETWORK"
    SECRET_USE = "SECRET_USE"
    FLASH = "FLASH"
    DEBUG = "DEBUG"
    HARDWARE_CONTROL = "HARDWARE_CONTROL"
    ACTUATOR_ENABLE = "ACTUATOR_ENABLE"
    DELETE = "DELETE"
    PLUGIN_INSTALL = "PLUGIN_INSTALL"
    KNOWLEDGE_PROMOTE = "KNOWLEDGE_PROMOTE"
    EXPORT_PRIVATE = "EXPORT_PRIVATE"


class TraceabilityRelation(StrEnum):
    IMPLEMENTS = "IMPLEMENTS"
    DERIVED_FROM = "DERIVED_FROM"
    VERIFIED_BY = "VERIFIED_BY"
    AFFECTS = "AFFECTS"
    DEPENDS_ON = "DEPENDS_ON"
    GENERATED_FROM = "GENERATED_FROM"
    INVALIDATES = "INVALIDATES"


class DependencyKind(StrEnum):
    """Engineering Dependency Graph edge semantics (M18)."""

    INPUT = "INPUT"
    DERIVATION = "DERIVATION"
    GENERATION = "GENERATION"
    CONFIGURATION = "CONFIGURATION"
    SELECTION = "SELECTION"
    VERIFICATION = "VERIFICATION"
    EVIDENCE = "EVIDENCE"


class InvalidationPolicy(StrEnum):
    """How an upstream semantic or validity change affects a dependent."""

    NONE = "NONE"
    SEMANTIC_CHANGE_STALE = "SEMANTIC_CHANGE_STALE"
    SOURCE_INVALID_STALE = "SOURCE_INVALID_STALE"
    SOURCE_INVALID_INVALID = "SOURCE_INVALID_INVALID"
    SEMANTIC_CHANGE_STALE_SOURCE_INVALID_INVALID = "SEMANTIC_CHANGE_STALE_SOURCE_INVALID_INVALID"


class DependencyNodeStatus(StrEnum):
    """Graph-owned status; it does not rewrite historical run statuses."""

    CURRENT = "CURRENT"
    STALE = "STALE"
    INVALID = "INVALID"
    UNKNOWN = "UNKNOWN"


class ChangeObservation(StrEnum):
    NON_SEMANTIC = "NON_SEMANTIC"
    SEMANTIC_CHANGED = "SEMANTIC_CHANGED"
    SOURCE_INVALID = "SOURCE_INVALID"


class ImpactAction(StrEnum):
    REVALIDATE = "REVALIDATE"
    REGENERATE = "REGENERATE"
    REBUILD = "REBUILD"
    RERUN_TEST = "RERUN_TEST"
    RERUN_REVIEW = "RERUN_REVIEW"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class EngineeringDimension(StrEnum):
    """FIX-02 frozen dimensions used by every normalized engineering value."""

    VOLTAGE = "VOLTAGE"
    CURRENT = "CURRENT"
    RESISTANCE = "RESISTANCE"
    CAPACITANCE = "CAPACITANCE"
    INDUCTANCE = "INDUCTANCE"
    FREQUENCY = "FREQUENCY"
    TIME = "TIME"
    TEMPERATURE = "TEMPERATURE"
    ANGLE = "ANGLE"
    ANGULAR_VELOCITY = "ANGULAR_VELOCITY"
    ANGULAR_ACCELERATION = "ANGULAR_ACCELERATION"
    LENGTH = "LENGTH"
    POWER = "POWER"
    ENERGY = "ENERGY"
    DIMENSIONLESS = "DIMENSIONLESS"


class VerificationLevel(StrEnum):
    AI_INFERRED = "AI_INFERRED"
    REFERENCE_SUPPORTED = "REFERENCE_SUPPORTED"
    DOCUMENT_VERIFIED = "DOCUMENT_VERIFIED"
    RULE_VERIFIED = "RULE_VERIFIED"
    TOOL_VERIFIED = "TOOL_VERIFIED"
    SIMULATION_VERIFIED = "SIMULATION_VERIFIED"
    HARDWARE_VERIFIED = "HARDWARE_VERIFIED"
    USER_CONFIRMED = "USER_CONFIRMED"
    IMPORT_VERIFIED = "IMPORT_VERIFIED"


class ClaimLifecycle(StrEnum):
    CANDIDATE = "CANDIDATE"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    CONFLICTED = "CONFLICTED"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"
    REJECTED = "REJECTED"


class ClaimConflictType(StrEnum):
    VALUE_MISMATCH = "VALUE_MISMATCH"


class ClaimConflictStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"


class ClaimConflictStrategy(StrEnum):
    SOURCE_PRIORITY = "SOURCE_PRIORITY"
    SOURCE_VERSION = "SOURCE_VERSION"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class DocumentType(StrEnum):
    DATASHEET = "DATASHEET"
    REFERENCE_MANUAL = "REFERENCE_MANUAL"
    ERRATA = "ERRATA"
    APPLICATION_NOTE = "APPLICATION_NOTE"
    USER_DOCUMENT = "USER_DOCUMENT"
    UNKNOWN = "UNKNOWN"


class DocumentParseStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    FAILED = "FAILED"


class DeviceCategory(StrEnum):
    MCU = "MCU"
    SENSOR = "SENSOR"
    POWER_DEVICE = "POWER_DEVICE"
    BOARD = "BOARD"
    PERIPHERAL = "PERIPHERAL"
    UNKNOWN = "UNKNOWN"


class DeviceMergeConflictType(StrEnum):
    SCALAR_MISMATCH = "SCALAR_MISMATCH"
    PIN_FUNCTION_MISMATCH = "PIN_FUNCTION_MISMATCH"


class EngineeringErrorCode(StrEnum):
    """Stable API error catalog, including the FIX-08 additions."""

    VALIDATION_ERROR = "VALIDATION_ERROR"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    DOCUMENT_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"
    CLAIM_CONFLICT = "CLAIM_CONFLICT"
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    PIN_CONFLICT = "PIN_CONFLICT"
    PIN_FUNCTION_INVALID = "PIN_FUNCTION_INVALID"
    INVALID_REQUIREMENT = "INVALID_REQUIREMENT"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    BUILD_FAILED = "BUILD_FAILED"
    ERC_FAILED = "ERC_FAILED"
    STATIC_ANALYSIS_FAILED = "STATIC_ANALYSIS_FAILED"
    TOOL_UNAVAILABLE = "TOOL_UNAVAILABLE"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE"
    PERMISSION_REQUIRED = "PERMISSION_REQUIRED"
    RESOURCE_BUSY = "RESOURCE_BUSY"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    KNOWLEDGE_SCOPE_DENIED = "KNOWLEDGE_SCOPE_DENIED"
    REPOSITORY_UNTRUSTED = "REPOSITORY_UNTRUSTED"
    JOB_CANCELLED = "JOB_CANCELLED"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    SOURCE_REVISION_CONFLICT = "SOURCE_REVISION_CONFLICT"
    DOMAIN_COMPOSITION_CONFLICT = "DOMAIN_COMPOSITION_CONFLICT"
    DOMAIN_DEPENDENCY_MISSING = "DOMAIN_DEPENDENCY_MISSING"
    DOMAIN_INCOMPATIBLE = "DOMAIN_INCOMPATIBLE"
    DOMAIN_NOT_FOUND = "DOMAIN_NOT_FOUND"
    DOMAIN_CONFIGURATION_INVALID = "DOMAIN_CONFIGURATION_INVALID"
    COMMISSIONING_REQUIRED = "COMMISSIONING_REQUIRED"
    COMMISSIONING_BLOCKED = "COMMISSIONING_BLOCKED"
    SAFETY_LIMIT_VIOLATION = "SAFETY_LIMIT_VIOLATION"
    TARGET_IDENTITY_MISMATCH = "TARGET_IDENTITY_MISMATCH"
    SAFE_STATE_FAILED = "SAFE_STATE_FAILED"
    EMERGENCY_STOP_ACTIVE = "EMERGENCY_STOP_ACTIVE"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    EVENT_DELIVERY_FAILED = "EVENT_DELIVERY_FAILED"
    INDEX_REBUILD_REQUIRED = "INDEX_REBUILD_REQUIRED"
    BUILD_INPUT_UNDECLARED = "BUILD_INPUT_UNDECLARED"
    SANDBOX_VIOLATION = "SANDBOX_VIOLATION"
    ARCHIVE_UNSAFE = "ARCHIVE_UNSAFE"
    COMMAND_NOT_ALLOWED = "COMMAND_NOT_ALLOWED"
    NETWORK_DENIED = "NETWORK_DENIED"
    RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
    COMPONENT_UNAVAILABLE = "COMPONENT_UNAVAILABLE"
    COMPONENT_VERSION_UNRESOLVED = "COMPONENT_VERSION_UNRESOLVED"
    COMPONENT_INCOMPATIBLE = "COMPONENT_INCOMPATIBLE"
    COMPONENT_HASH_MISMATCH = "COMPONENT_HASH_MISMATCH"
    COMPONENT_LICENSE_BLOCKED = "COMPONENT_LICENSE_BLOCKED"
    COMPONENT_REFERENCE_ONLY = "COMPONENT_REFERENCE_ONLY"
    DEPENDENCY_CONFLICT = "DEPENDENCY_CONFLICT"
    DEPENDENCY_CYCLE = "DEPENDENCY_CYCLE"
    DEPENDENCY_LOCK_REQUIRED = "DEPENDENCY_LOCK_REQUIRED"
    DEPENDENCY_LOCK_STALE = "DEPENDENCY_LOCK_STALE"
    COMPONENT_MATERIALIZATION_FAILED = "COMPONENT_MATERIALIZATION_FAILED"
    TOOLCHAIN_INCOMPATIBLE = "TOOLCHAIN_INCOMPATIBLE"
    DEVICE_BUILD_UNAVAILABLE = "DEVICE_BUILD_UNAVAILABLE"
