"""Canonical Core enums shared by storage, API, and generated clients."""

from enum import StrEnum


class ProjectStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class ArtifactStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    INVALID = "INVALID"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"


class EvidenceType(StrEnum):
    DOCUMENT = "DOCUMENT"
    DEVICE_DB = "DEVICE_DB"
    REPOSITORY = "REPOSITORY"
    RULE = "RULE"
    TOOL = "TOOL"
    SIMULATION = "SIMULATION"
    HARDWARE_TEST = "HARDWARE_TEST"
    USER_CONFIRMATION = "USER_CONFIRMATION"
    IMPORTED_PROJECT = "IMPORTED_PROJECT"


class IssueSeverity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IssueStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class DecisionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"


class JobStatus(StrEnum):
    """FIX-08 canonical Job state machine."""

    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    BLOCKED_PERMISSION = "BLOCKED_PERMISSION"
    BLOCKED_RESOURCE = "BLOCKED_RESOURCE"
    RECOVERING = "RECOVERING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    FAILED_NEEDS_RECONCILE = "FAILED_NEEDS_RECONCILE"
    CANCELLED = "CANCELLED"


class Permission(StrEnum):
    """FIX-08 canonical permission catalog."""

    READ = "READ"
    WRITE = "WRITE"
    BUILD = "BUILD"
    NETWORK = "NETWORK"
    SECRET_USE = "SECRET_USE"
    FLASH = "FLASH"
    DEBUG = "DEBUG"
    HARDWARE_CONTROL = "HARDWARE_CONTROL"
    ACTUATOR_ENABLE = "ACTUATOR_ENABLE"
    DELETE = "DELETE"
    PLUGIN_INSTALL = "PLUGIN_INSTALL"
    KNOWLEDGE_PROMOTE = "KNOWLEDGE_PROMOTE"
    EXPORT_PRIVATE = "EXPORT_PRIVATE"


class TraceabilityRelation(StrEnum):
    IMPLEMENTS = "IMPLEMENTS"
    DERIVED_FROM = "DERIVED_FROM"
    VERIFIED_BY = "VERIFIED_BY"
    AFFECTS = "AFFECTS"
    DEPENDS_ON = "DEPENDS_ON"
    GENERATED_FROM = "GENERATED_FROM"
    INVALIDATES = "INVALIDATES"


class EngineeringErrorCode(StrEnum):
    """Stable API error catalog, including the FIX-08 additions."""

    VALIDATION_ERROR = "VALIDATION_ERROR"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    DOCUMENT_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"
    CLAIM_CONFLICT = "CLAIM_CONFLICT"
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    PIN_CONFLICT = "PIN_CONFLICT"
    PIN_FUNCTION_INVALID = "PIN_FUNCTION_INVALID"
    INVALID_REQUIREMENT = "INVALID_REQUIREMENT"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    BUILD_FAILED = "BUILD_FAILED"
    ERC_FAILED = "ERC_FAILED"
    STATIC_ANALYSIS_FAILED = "STATIC_ANALYSIS_FAILED"
    TOOL_UNAVAILABLE = "TOOL_UNAVAILABLE"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE"
    PERMISSION_REQUIRED = "PERMISSION_REQUIRED"
    RESOURCE_BUSY = "RESOURCE_BUSY"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    KNOWLEDGE_SCOPE_DENIED = "KNOWLEDGE_SCOPE_DENIED"
    REPOSITORY_UNTRUSTED = "REPOSITORY_UNTRUSTED"
    JOB_CANCELLED = "JOB_CANCELLED"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    SOURCE_REVISION_CONFLICT = "SOURCE_REVISION_CONFLICT"
    DOMAIN_COMPOSITION_CONFLICT = "DOMAIN_COMPOSITION_CONFLICT"
    DOMAIN_DEPENDENCY_MISSING = "DOMAIN_DEPENDENCY_MISSING"
    DOMAIN_INCOMPATIBLE = "DOMAIN_INCOMPATIBLE"
    COMMISSIONING_REQUIRED = "COMMISSIONING_REQUIRED"
    COMMISSIONING_BLOCKED = "COMMISSIONING_BLOCKED"
    SAFETY_LIMIT_VIOLATION = "SAFETY_LIMIT_VIOLATION"
    TARGET_IDENTITY_MISMATCH = "TARGET_IDENTITY_MISMATCH"
    SAFE_STATE_FAILED = "SAFE_STATE_FAILED"
    EMERGENCY_STOP_ACTIVE = "EMERGENCY_STOP_ACTIVE"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    EVENT_DELIVERY_FAILED = "EVENT_DELIVERY_FAILED"
    INDEX_REBUILD_REQUIRED = "INDEX_REBUILD_REQUIRED"
    BUILD_INPUT_UNDECLARED = "BUILD_INPUT_UNDECLARED"
