// Generated by `eea openapi typescript`; do not edit manually.

export interface ApiEnvelope<T> {
  success: true;
  data: T;
  request_id: string;
}

export const artifactStatusValues = [
  "CURRENT",
  "STALE",
  "INVALID",
  "DEPRECATED",
  "ARCHIVED"
] as const;
export type ArtifactStatus = (typeof artifactStatusValues)[number];

export const claimConflictStatusValues = [
  "OPEN",
  "RESOLVED"
] as const;
export type ClaimConflictStatus = (typeof claimConflictStatusValues)[number];

export const claimConflictStrategyValues = [
  "SOURCE_PRIORITY",
  "SOURCE_VERSION",
  "MANUAL_REVIEW"
] as const;
export type ClaimConflictStrategy = (typeof claimConflictStrategyValues)[number];

export const claimConflictTypeValues = [
  "VALUE_MISMATCH"
] as const;
export type ClaimConflictType = (typeof claimConflictTypeValues)[number];

export const claimLifecycleValues = [
  "CANDIDATE",
  "ACTIVE",
  "SUPERSEDED",
  "CONFLICTED",
  "DEPRECATED",
  "ARCHIVED",
  "REJECTED"
] as const;
export type ClaimLifecycle = (typeof claimLifecycleValues)[number];

export const decisionStatusValues = [
  "PROPOSED",
  "ACCEPTED",
  "SUPERSEDED",
  "REJECTED"
] as const;
export type DecisionStatus = (typeof decisionStatusValues)[number];

export const domainActivationStatusValues = [
  "ACTIVE",
  "DISABLED",
  "INCOMPATIBLE",
  "BLOCKED"
] as const;
export type DomainActivationStatus = (typeof domainActivationStatusValues)[number];

export const domainRulePhaseValues = [
  "PRE_SCHEMA",
  "PRE_DESIGN",
  "PRE_GENERATION",
  "POST_GENERATION",
  "PRE_EXECUTION",
  "POST_EXECUTION",
  "RELEASE_GATE"
] as const;
export type DomainRulePhase = (typeof domainRulePhaseValues)[number];

export const domainTrustTierValues = [
  "bundled",
  "signed_trusted",
  "community_untrusted"
] as const;
export type DomainTrustTier = (typeof domainTrustTierValues)[number];

export const deviceCategoryValues = [
  "MCU",
  "SENSOR",
  "POWER_DEVICE",
  "BOARD",
  "PERIPHERAL",
  "UNKNOWN"
] as const;
export type DeviceCategory = (typeof deviceCategoryValues)[number];

export const deviceMergeConflictTypeValues = [
  "SCALAR_MISMATCH",
  "PIN_FUNCTION_MISMATCH"
] as const;
export type DeviceMergeConflictType = (typeof deviceMergeConflictTypeValues)[number];

export const documentParseStatusValues = [
  "UPLOADED",
  "PARSING",
  "PARSED",
  "FAILED"
] as const;
export type DocumentParseStatus = (typeof documentParseStatusValues)[number];

export const documentTypeValues = [
  "DATASHEET",
  "REFERENCE_MANUAL",
  "ERRATA",
  "APPLICATION_NOTE",
  "USER_DOCUMENT",
  "UNKNOWN"
] as const;
export type DocumentType = (typeof documentTypeValues)[number];

export const engineeringDimensionValues = [
  "VOLTAGE",
  "CURRENT",
  "RESISTANCE",
  "CAPACITANCE",
  "INDUCTANCE",
  "FREQUENCY",
  "TIME",
  "TEMPERATURE",
  "ANGLE",
  "ANGULAR_VELOCITY",
  "ANGULAR_ACCELERATION",
  "LENGTH",
  "POWER",
  "ENERGY",
  "DIMENSIONLESS"
] as const;
export type EngineeringDimension = (typeof engineeringDimensionValues)[number];

export const engineeringErrorCodeValues = [
  "VALIDATION_ERROR",
  "PROJECT_NOT_FOUND",
  "DOCUMENT_PARSE_FAILED",
  "CLAIM_CONFLICT",
  "DEVICE_NOT_FOUND",
  "PIN_CONFLICT",
  "PIN_FUNCTION_INVALID",
  "INVALID_REQUIREMENT",
  "REVISION_CONFLICT",
  "BUILD_FAILED",
  "ERC_FAILED",
  "STATIC_ANALYSIS_FAILED",
  "TOOL_UNAVAILABLE",
  "CAPABILITY_UNAVAILABLE",
  "AI_PROVIDER_UNAVAILABLE",
  "PERMISSION_REQUIRED",
  "RESOURCE_BUSY",
  "BUDGET_EXCEEDED",
  "KNOWLEDGE_SCOPE_DENIED",
  "REPOSITORY_UNTRUSTED",
  "JOB_CANCELLED",
  "SCHEMA_VERSION_UNSUPPORTED",
  "AUTH_REQUIRED",
  "SOURCE_REVISION_CONFLICT",
  "DOMAIN_COMPOSITION_CONFLICT",
  "DOMAIN_DEPENDENCY_MISSING",
  "DOMAIN_INCOMPATIBLE",
  "DOMAIN_NOT_FOUND",
  "DOMAIN_CONFIGURATION_INVALID",
  "COMMISSIONING_REQUIRED",
  "COMMISSIONING_BLOCKED",
  "SAFETY_LIMIT_VIOLATION",
  "TARGET_IDENTITY_MISMATCH",
  "SAFE_STATE_FAILED",
  "EMERGENCY_STOP_ACTIVE",
  "RECOVERY_REQUIRED",
  "EVENT_DELIVERY_FAILED",
  "INDEX_REBUILD_REQUIRED",
  "BUILD_INPUT_UNDECLARED",
  "SANDBOX_VIOLATION",
  "ARCHIVE_UNSAFE",
  "COMMAND_NOT_ALLOWED",
  "NETWORK_DENIED",
  "RESOURCE_LIMIT_EXCEEDED",
  "COMPONENT_UNAVAILABLE",
  "COMPONENT_VERSION_UNRESOLVED",
  "COMPONENT_INCOMPATIBLE",
  "COMPONENT_HASH_MISMATCH",
  "COMPONENT_LICENSE_BLOCKED",
  "COMPONENT_REFERENCE_ONLY",
  "DEPENDENCY_CONFLICT",
  "DEPENDENCY_CYCLE",
  "DEPENDENCY_LOCK_REQUIRED",
  "DEPENDENCY_LOCK_STALE",
  "COMPONENT_MATERIALIZATION_FAILED",
  "TOOLCHAIN_INCOMPATIBLE",
  "DEVICE_BUILD_UNAVAILABLE"
] as const;
export type EngineeringErrorCode = (typeof engineeringErrorCodeValues)[number];

export const evidenceTypeValues = [
  "DOCUMENT",
  "DEVICE_DB",
  "REPOSITORY",
  "RULE",
  "TOOL",
  "SIMULATION",
  "HARDWARE_TEST",
  "USER_CONFIRMATION",
  "IMPORTED_PROJECT"
] as const;
export type EvidenceType = (typeof evidenceTypeValues)[number];

export const issueSeverityValues = [
  "INFO",
  "LOW",
  "MEDIUM",
  "HIGH",
  "CRITICAL"
] as const;
export type IssueSeverity = (typeof issueSeverityValues)[number];

export const issueStatusValues = [
  "OPEN",
  "RESOLVED",
  "IGNORED"
] as const;
export type IssueStatus = (typeof issueStatusValues)[number];

export const jobStatusValues = [
  "QUEUED",
  "RUNNING",
  "BLOCKED_PERMISSION",
  "BLOCKED_RESOURCE",
  "RECOVERING",
  "SUCCESS",
  "FAILED",
  "FAILED_NEEDS_RECONCILE",
  "CANCELLED"
] as const;
export type JobStatus = (typeof jobStatusValues)[number];

export const permissionValues = [
  "READ",
  "WRITE",
  "BUILD",
  "NETWORK",
  "SECRET_USE",
  "FLASH",
  "DEBUG",
  "HARDWARE_CONTROL",
  "ACTUATOR_ENABLE",
  "DELETE",
  "PLUGIN_INSTALL",
  "KNOWLEDGE_PROMOTE",
  "EXPORT_PRIVATE"
] as const;
export type Permission = (typeof permissionValues)[number];

export const projectStatusValues = [
  "DRAFT",
  "ACTIVE",
  "ARCHIVED"
] as const;
export type ProjectStatus = (typeof projectStatusValues)[number];

export const requirementFieldStatusValues = [
  "PRESENT",
  "MISSING",
  "UNKNOWN",
  "AMBIGUOUS"
] as const;
export type RequirementFieldStatus = (typeof requirementFieldStatusValues)[number];

export const requirementPriorityValues = [
  "MUST",
  "SHOULD",
  "COULD",
  "UNKNOWN"
] as const;
export type RequirementPriority = (typeof requirementPriorityValues)[number];

export const requirementStatusValues = [
  "CANDIDATE",
  "INCOMPLETE",
  "AMBIGUOUS",
  "COMPLETE",
  "ACCEPTED",
  "REJECTED"
] as const;
export type RequirementStatus = (typeof requirementStatusValues)[number];

export const requirementTypeValues = [
  "FUNCTIONAL",
  "PERFORMANCE",
  "INTERFACE",
  "SAFETY",
  "CONSTRAINT",
  "UNKNOWN"
] as const;
export type RequirementType = (typeof requirementTypeValues)[number];

export const requirementValueTypeValues = [
  "TEXT",
  "NUMBER",
  "BOOLEAN",
  "ENUM",
  "ENGINEERING_VALUE",
  "OBJECT",
  "LIST"
] as const;
export type RequirementValueType = (typeof requirementValueTypeValues)[number];

export const staticAnalysisStatusValues = [
  "PASS",
  "FAIL",
  "UNKNOWN",
  "BLOCKED"
] as const;
export type StaticAnalysisStatus = (typeof staticAnalysisStatusValues)[number];

export const traceabilityRelationValues = [
  "IMPLEMENTS",
  "DERIVED_FROM",
  "VERIFIED_BY",
  "AFFECTS",
  "DEPENDS_ON",
  "GENERATED_FROM",
  "INVALIDATES"
] as const;
export type TraceabilityRelation = (typeof traceabilityRelationValues)[number];

export const automationLevelValues = [
  "AUTOMATED",
  "SEMI_AUTOMATED",
  "MANUAL"
] as const;
export type AutomationLevel = (typeof automationLevelValues)[number];

export const testExecutionStatusValues = [
  "PASS",
  "FAIL",
  "UNKNOWN",
  "BLOCKED",
  "SKIPPED"
] as const;
export type TestExecutionStatus = (typeof testExecutionStatusValues)[number];

export const testTypeValues = [
  "REQUIREMENT",
  "BUILD",
  "STATIC_ANALYSIS",
  "ERC",
  "PROTOCOL",
  "INTEGRATION",
  "MANUAL"
] as const;
export type TestType = (typeof testTypeValues)[number];

export const verificationLevelValues = [
  "AI_INFERRED",
  "REFERENCE_SUPPORTED",
  "DOCUMENT_VERIFIED",
  "RULE_VERIFIED",
  "TOOL_VERIFIED",
  "SIMULATION_VERIFIED",
  "HARDWARE_VERIFIED",
  "USER_CONFIRMED",
  "IMPORT_VERIFIED"
] as const;
export type VerificationLevel = (typeof verificationLevelValues)[number];

export interface ApiError {
  code: EngineeringErrorCode;
  message: string;
  details: Record<string, unknown>;
}

export interface ProjectData {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  name: string;
  description: string;
  status: ProjectStatus;
}

export interface OutboxStatusData {
  pending: number;
  processing: number;
  retry: number;
  processed: number;
  dead_letter: number;
  total: number;
}

export interface RecoveryStatusData {
  status: "CLEAN" | "RECOVERY_REQUIRED";
  pending: number;
  retry: number;
  dead_letter: number;
  reconcile_required: number;
  interrupted_jobs: number;
}

export interface RecoveryReconcileRequest {
  project_id?: string | null;
  limit?: number;
}

export interface RecoveryReconcileData {
  reclaimed: number;
  dispatched: Record<string, number>;
  reconcile_required: number;
  project: RecoveryStatusData | null;
}

export interface DomainRuleContribution {
  rule_id: string;
  rule_version: string;
  phase: DomainRulePhase;
  inputs: string[];
  severity: IssueSeverity;
  priority: number;
  safety_mode: "ADDITIVE";
}

export interface DomainGeneratorContribution {
  generator_id: string;
  version: string;
  consumes: string[];
  produces: string[];
  requires_capabilities: string[];
  before: string[];
  after: string[];
  deterministic: boolean;
  side_effects: boolean;
}

export interface DomainContextContribution {
  context_id: string;
  keys: string[];
  description: string;
}

export interface DomainValidationDiagnostic {
  rule_id: string;
  status: "PASS" | "FAIL" | "UNKNOWN" | "BLOCKED";
  message: string;
  details: Record<string, unknown>;
}

export interface DomainValidationResult {
  domain_id: string;
  diagnostics: DomainValidationDiagnostic[];
}

export interface DomainUIContribution {
  extension_id: string;
  kind: "navigation" | "action" | "form";
  label: string;
  route: string;
  json_schema: Record<string, unknown>;
  action: string | null;
}

export interface DomainDescriptorData {
  id: string;
  plugin_id: string;
  name: string;
  version: string;
  api_version: string;
  schema_version: string;
  trust_tier: DomainTrustTier;
  entrypoint: string;
  capabilities: string[];
  required_capabilities: string[];
  requires_domains: string[];
  optional_domains: string[];
  conflicts_with: string[];
  priority: number;
  rule_phases: DomainRulePhase[];
  generator_phases: string[];
  migration_provider: string | null;
  context_contributions: string[];
  ui_contributions: string[];
  permissions: Permission[];
}

export interface DomainAvailableData {
  descriptor: DomainDescriptorData;
  active: boolean;
}

export interface DomainActivationData {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string;
  domain_id: string;
  plugin_id: string;
  plugin_version: string;
  domain_schema_version: string;
  configuration_schema_version: string;
  configuration_schema_hash: string | null;
  status: DomainActivationStatus;
  configuration: Record<string, unknown>;
  activated_at: string;
  activated_by: string;
  capability_snapshot: Record<string, unknown>;
  dependency_snapshot: Record<string, unknown>;
}

export interface DomainCompositionData {
  active_domain_ids: string[];
  ordered_domain_ids: string[];
  dependency_edges: string[][];
  capability_routes: Record<string, string>;
  rules: DomainRuleContribution[];
  generators: DomainGeneratorContribution[];
  context_contributions: DomainContextContribution[];
  ui_contributions: DomainUIContribution[];
  validation_results: DomainValidationResult[];
}

export interface DomainSchemaData {
  domain_id: string;
  schema_version: string;
  json_schema: Record<string, unknown>;
}

export interface DomainActivationRequest {
  configuration: Record<string, unknown> | null;
  activated_by: string;
}

export interface DomainValidationRequest {
  domain_ids: string[];
  selected_capabilities: Record<string, string>;
  domain_ir?: Record<string, unknown> | null;
  mcu_config_id?: string | null;
}

export interface DocumentUploadRequest {
  filename: string;
  content_base64: string;
  document_type: DocumentType;
  vendor: string | null;
  product: string | null;
  version_label: string | null;
}

export interface DocumentData {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string | null;
  filename: string;
  document_type: DocumentType;
  vendor: string | null;
  product: string | null;
  version_label: string | null;
  content_hash: string;
  storage_uri: string;
  parse_status: DocumentParseStatus;
  parse_error: string | null;
}

export interface EvidenceCreateRequest {
  evidence_type: EvidenceType;
  locator: Record<string, unknown>;
  source_uri: string | null;
  content_hash: string | null;
  summary: string;
}

export interface EvidenceData {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string | null;
  evidence_type: EvidenceType;
  locator: Record<string, unknown>;
  source_uri: string | null;
  content_hash: string | null;
  files: string[];
  summary: string;
}

export interface CANTransportConfig {
  nominal_bitrate: number;
  frame_kind: string;
  data_bitrate: number | null;
  fd_brs: boolean | null;
}

export interface ProtocolTransport {
  transport_id: string;
  name: string;
  transport_type: string;
  can: CANTransportConfig;
}

export interface ProtocolField {
  field_id: string;
  name: string;
  bit_offset: number;
  bit_length: number;
  endian: string;
  signed: boolean;
  scale: number;
  offset: number;
  unit: string;
  minimum: number | null;
  maximum: number | null;
}

export interface ProtocolMessage {
  message_id: string;
  name: string;
  transport_ref: string;
  can_id: number;
  extended_id: boolean;
  payload_length_bytes: number;
  fields: ProtocolField[];
  requirement_ids: string[];
  description: string;
}

export interface ProtocolDefinition {
  version_label: string;
  transports: ProtocolTransport[];
  messages: ProtocolMessage[];
  requirement_ids: string[];
  evidence_ids: string[];
}

export type ProtocolCreateRequest = ProtocolDefinition;

export interface ProtocolIR extends ProtocolDefinition {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string;
  input_hash: string;
}

export interface ProtocolUpdateRequest extends ProtocolDefinition {
  expected_revision?: number | null;
}

export interface ProtocolValidationDiagnostic {
  rule_id: string;
  status: "PASS" | "FAIL" | "UNKNOWN" | "BLOCKED";
  message: string;
  details: Record<string, unknown>;
}

export interface ProtocolValidationResult {
  protocol_id: string;
  protocol_revision: number;
  input_hash: string;
  diagnostics: ProtocolValidationDiagnostic[];
}

export interface GeneratedProtocolOutput {
  target: "C" | "PYTHON" | "DBC" | "MARKDOWN";
  path: string;
  content: string;
  content_hash: string;
  input_hash: string;
  protocol_revision: number;
  generator_version: string;
}

export interface ProtocolGenerationBundle {
  protocol_id: string;
  protocol_revision: number;
  input_hash: string;
  generator_version: string;
  outputs: GeneratedProtocolOutput[];
}

export interface ProtocolValidateRequest {
  protocol_id?: string | null;
  revision?: number | null;
}

export interface ProtocolGenerateRequest {
  protocol_id?: string | null;
  revision?: number | null;
}

export interface TestCase {
  id: string;
  code: string;
  title: string;
  type: TestType;
  requirement_ids: string[];
  preconditions: string[];
  setup: string[];
  inputs: Record<string, unknown>;
  steps: string[];
  expected: string[];
  timeout: string;
  pass_condition: string;
  cleanup: string[];
  automation_level: AutomationLevel;
  executor_id: string | null;
  executor_config: Record<string, unknown>;
  required: boolean;
  evidence_ids: string[];
}

export interface TestIR {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string;
  requirement_ids: string[];
  cases: TestCase[];
  input_hash: string;
  generator_version: string;
  policy_version: string;
  evidence_ids: string[];
}

export interface TestCaseResult {
  id: string;
  test_case_id: string;
  test_case_code: string;
  status: TestExecutionStatus;
  duration_ms: number;
  message: string;
  observed: unknown;
  expected: unknown;
  evidence_ids: string[];
  executor_id: string | null;
  failure: Record<string, unknown> | null;
}

export interface TestRun {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string;
  test_ir_id: string;
  test_ir_revision: number;
  test_input_hash: string;
  source_revision_id: string;
  status: TestExecutionStatus;
  started_at: string;
  finished_at: string | null;
  case_results: TestCaseResult[];
  tool_versions: Record<string, string>;
  evidence_ids: string[];
}

export interface TestGenerationData {
  test_ir: TestIR;
  coverage_gaps: string[];
}

export interface TestRunRequest {
  test_ir_id?: string | null;
  source_revision_id: string;
}

export interface CoverageData {
  total_requirements: number;
  release_critical_requirements: number;
  covered_requirements: number;
  verified_requirements: number;
  design_coverage_ratio: number;
  verification_coverage_ratio: number;
  uncovered_requirement_ids: string[];
  unexecuted_requirement_ids: string[];
  failing_requirement_ids: string[];
  blocked_requirement_ids: string[];
  unknown_requirement_ids: string[];
}

export interface TraceabilityData {
  edges: Record<string, unknown>[];
  coverage: CoverageData;
  orphan_tests: string[];
  uncovered_requirements: string[];
}

export interface ReviewFinding {
  code: string;
  title: string;
  message: string;
  source_kind: string;
  source_ref: string;
  severity: IssueSeverity;
  status: TestExecutionStatus;
  affected_refs: string[];
  evidence_ids: string[];
  deterministic: boolean;
  dedupe_key: string;
}

export interface ReviewRun {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string;
  source_revision_id: string;
  policy_version: string;
  input_hash: string;
  build_run_id: string | null;
  static_analysis_id: string | null;
  test_run_id: string | null;
  test_ir_id: string | null;
  test_ir_revision: number | null;
  protocol_id: string | null;
  protocol_revision: number | null;
  status: TestExecutionStatus;
  findings: ReviewFinding[];
  issue_ids: string[];
}

export interface ReviewRequest {
  source_revision_id: string;
  test_ir_id?: string | null;
  test_run_id?: string | null;
  build_run_id?: string | null;
  static_analysis_id?: string | null;
  schematic_id?: string | null;
  require_build?: boolean;
  require_static_analysis?: boolean;
  require_erc?: boolean;
}

export interface IssueData {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  project_id: string;
  code: string;
  title: string;
  description: string;
  severity: IssueSeverity;
  status: IssueStatus;
  claim_ids: string[];
  evidence_ids: string[];
  resolution: string | null;
  dedupe_key: string | null;
  source_kind: string | null;
  source_ref: string | null;
  affected_refs: string[];
  first_seen_at: string | null;
  last_seen_at: string | null;
  occurrence_count: number;
  last_review_id: string | null;
}

export interface IssueMutationRequest {
  project_id: string;
  reason: string;
  expected_revision?: number | null;
}
