// Generated by `eea openapi typescript`; do not edit manually.

export interface ApiEnvelope<T> {
  success: true;
  data: T;
  request_id: string;
}

export const artifactStatusValues = [
  "CURRENT",
  "STALE",
  "INVALID",
  "DEPRECATED",
  "ARCHIVED"
] as const;
export type ArtifactStatus = (typeof artifactStatusValues)[number];

export const claimConflictStatusValues = [
  "OPEN",
  "RESOLVED"
] as const;
export type ClaimConflictStatus = (typeof claimConflictStatusValues)[number];

export const claimConflictStrategyValues = [
  "SOURCE_PRIORITY",
  "SOURCE_VERSION",
  "MANUAL_REVIEW"
] as const;
export type ClaimConflictStrategy = (typeof claimConflictStrategyValues)[number];

export const claimConflictTypeValues = [
  "VALUE_MISMATCH"
] as const;
export type ClaimConflictType = (typeof claimConflictTypeValues)[number];

export const claimLifecycleValues = [
  "CANDIDATE",
  "ACTIVE",
  "SUPERSEDED",
  "CONFLICTED",
  "DEPRECATED",
  "ARCHIVED",
  "REJECTED"
] as const;
export type ClaimLifecycle = (typeof claimLifecycleValues)[number];

export const decisionStatusValues = [
  "PROPOSED",
  "ACCEPTED",
  "SUPERSEDED",
  "REJECTED"
] as const;
export type DecisionStatus = (typeof decisionStatusValues)[number];

export const deviceCategoryValues = [
  "MCU",
  "SENSOR",
  "POWER_DEVICE",
  "BOARD",
  "PERIPHERAL",
  "UNKNOWN"
] as const;
export type DeviceCategory = (typeof deviceCategoryValues)[number];

export const deviceMergeConflictTypeValues = [
  "SCALAR_MISMATCH",
  "PIN_FUNCTION_MISMATCH"
] as const;
export type DeviceMergeConflictType = (typeof deviceMergeConflictTypeValues)[number];

export const documentParseStatusValues = [
  "UPLOADED",
  "PARSING",
  "PARSED",
  "FAILED"
] as const;
export type DocumentParseStatus = (typeof documentParseStatusValues)[number];

export const documentTypeValues = [
  "DATASHEET",
  "REFERENCE_MANUAL",
  "ERRATA",
  "APPLICATION_NOTE",
  "USER_DOCUMENT",
  "UNKNOWN"
] as const;
export type DocumentType = (typeof documentTypeValues)[number];

export const engineeringDimensionValues = [
  "VOLTAGE",
  "CURRENT",
  "RESISTANCE",
  "CAPACITANCE",
  "INDUCTANCE",
  "FREQUENCY",
  "TIME",
  "TEMPERATURE",
  "ANGLE",
  "ANGULAR_VELOCITY",
  "LENGTH",
  "POWER",
  "ENERGY",
  "DIMENSIONLESS"
] as const;
export type EngineeringDimension = (typeof engineeringDimensionValues)[number];

export const engineeringErrorCodeValues = [
  "VALIDATION_ERROR",
  "PROJECT_NOT_FOUND",
  "DOCUMENT_PARSE_FAILED",
  "CLAIM_CONFLICT",
  "DEVICE_NOT_FOUND",
  "PIN_CONFLICT",
  "PIN_FUNCTION_INVALID",
  "INVALID_REQUIREMENT",
  "REVISION_CONFLICT",
  "BUILD_FAILED",
  "ERC_FAILED",
  "STATIC_ANALYSIS_FAILED",
  "TOOL_UNAVAILABLE",
  "CAPABILITY_UNAVAILABLE",
  "AI_PROVIDER_UNAVAILABLE",
  "PERMISSION_REQUIRED",
  "RESOURCE_BUSY",
  "BUDGET_EXCEEDED",
  "KNOWLEDGE_SCOPE_DENIED",
  "REPOSITORY_UNTRUSTED",
  "JOB_CANCELLED",
  "SCHEMA_VERSION_UNSUPPORTED",
  "AUTH_REQUIRED",
  "SOURCE_REVISION_CONFLICT",
  "DOMAIN_COMPOSITION_CONFLICT",
  "DOMAIN_DEPENDENCY_MISSING",
  "DOMAIN_INCOMPATIBLE",
  "COMMISSIONING_REQUIRED",
  "COMMISSIONING_BLOCKED",
  "SAFETY_LIMIT_VIOLATION",
  "TARGET_IDENTITY_MISMATCH",
  "SAFE_STATE_FAILED",
  "EMERGENCY_STOP_ACTIVE",
  "RECOVERY_REQUIRED",
  "EVENT_DELIVERY_FAILED",
  "INDEX_REBUILD_REQUIRED",
  "BUILD_INPUT_UNDECLARED"
] as const;
export type EngineeringErrorCode = (typeof engineeringErrorCodeValues)[number];

export const evidenceTypeValues = [
  "DOCUMENT",
  "DEVICE_DB",
  "REPOSITORY",
  "RULE",
  "TOOL",
  "SIMULATION",
  "HARDWARE_TEST",
  "USER_CONFIRMATION",
  "IMPORTED_PROJECT"
] as const;
export type EvidenceType = (typeof evidenceTypeValues)[number];

export const issueSeverityValues = [
  "INFO",
  "LOW",
  "MEDIUM",
  "HIGH",
  "CRITICAL"
] as const;
export type IssueSeverity = (typeof issueSeverityValues)[number];

export const issueStatusValues = [
  "OPEN",
  "RESOLVED",
  "IGNORED"
] as const;
export type IssueStatus = (typeof issueStatusValues)[number];

export const jobStatusValues = [
  "QUEUED",
  "RUNNING",
  "BLOCKED_PERMISSION",
  "BLOCKED_RESOURCE",
  "RECOVERING",
  "SUCCESS",
  "FAILED",
  "FAILED_NEEDS_RECONCILE",
  "CANCELLED"
] as const;
export type JobStatus = (typeof jobStatusValues)[number];

export const permissionValues = [
  "READ",
  "WRITE",
  "BUILD",
  "NETWORK",
  "SECRET_USE",
  "FLASH",
  "DEBUG",
  "HARDWARE_CONTROL",
  "ACTUATOR_ENABLE",
  "DELETE",
  "PLUGIN_INSTALL",
  "KNOWLEDGE_PROMOTE",
  "EXPORT_PRIVATE"
] as const;
export type Permission = (typeof permissionValues)[number];

export const projectStatusValues = [
  "DRAFT",
  "ACTIVE",
  "ARCHIVED"
] as const;
export type ProjectStatus = (typeof projectStatusValues)[number];

export const traceabilityRelationValues = [
  "IMPLEMENTS",
  "DERIVED_FROM",
  "VERIFIED_BY",
  "AFFECTS",
  "DEPENDS_ON",
  "GENERATED_FROM",
  "INVALIDATES"
] as const;
export type TraceabilityRelation = (typeof traceabilityRelationValues)[number];

export const verificationLevelValues = [
  "AI_INFERRED",
  "REFERENCE_SUPPORTED",
  "DOCUMENT_VERIFIED",
  "RULE_VERIFIED",
  "TOOL_VERIFIED",
  "SIMULATION_VERIFIED",
  "HARDWARE_VERIFIED",
  "USER_CONFIRMED",
  "IMPORT_VERIFIED"
] as const;
export type VerificationLevel = (typeof verificationLevelValues)[number];

export interface ApiError {
  code: EngineeringErrorCode;
  message: string;
  details: Record<string, unknown>;
}

export interface ProjectData {
  id: string;
  schema_version: string;
  revision: number;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  name: string;
  description: string;
  status: ProjectStatus;
}
