"""Small deterministic TypeScript contract generator for Core API types."""

import json
from enum import StrEnum

from eea_core.enums import (
    ArtifactStatus,
    ClaimConflictStatus,
    ClaimConflictStrategy,
    ClaimConflictType,
    ClaimLifecycle,
    DecisionStatus,
    DeviceCategory,
    DeviceMergeConflictType,
    DocumentParseStatus,
    DocumentType,
    DomainActivationStatus,
    DomainRulePhase,
    DomainTrustTier,
    EngineeringDimension,
    EngineeringErrorCode,
    EvidenceType,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    RequirementFieldStatus,
    RequirementPriority,
    RequirementStatus,
    RequirementType,
    RequirementValueType,
    StaticAnalysisStatus,
    TraceabilityRelation,
    VerificationLevel,
)
from eea_core.testing import AutomationLevel, TestExecutionStatus, TestType

CORE_ENUMS: tuple[type[StrEnum], ...] = (
    ArtifactStatus,
    ClaimConflictStatus,
    ClaimConflictStrategy,
    ClaimConflictType,
    ClaimLifecycle,
    DecisionStatus,
    DomainActivationStatus,
    DomainRulePhase,
    DomainTrustTier,
    DeviceCategory,
    DeviceMergeConflictType,
    DocumentParseStatus,
    DocumentType,
    EngineeringDimension,
    EngineeringErrorCode,
    EvidenceType,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    RequirementFieldStatus,
    RequirementPriority,
    RequirementStatus,
    RequirementType,
    RequirementValueType,
    StaticAnalysisStatus,
    TraceabilityRelation,
    AutomationLevel,
    TestExecutionStatus,
    TestType,
    VerificationLevel,
)


def _lower_camel(name: str) -> str:
    return name[0].lower() + name[1:]


def _render_enum(enum_type: type[StrEnum]) -> str:
    constant_name = f"{_lower_camel(enum_type.__name__)}Values"
    values = json.dumps([member.value for member in enum_type], indent=2)
    return (
        f"export const {constant_name} = {values} as const;\n"
        f"export type {enum_type.__name__} = (typeof {constant_name})[number];\n"
    )


def render_typescript_contract() -> str:
    sections = [
        "// Generated by `eea openapi typescript`; do not edit manually.\n",
        "export interface ApiEnvelope<T> {\n"
        "  success: true;\n"
        "  data: T;\n"
        "  request_id: string;\n"
        "}\n",
    ]
    sections.extend(_render_enum(enum_type) for enum_type in CORE_ENUMS)
    sections.extend(
        [
            "export interface ApiError {\n"
            "  code: EngineeringErrorCode;\n"
            "  message: string;\n"
            "  details: Record<string, unknown>;\n"
            "}\n",
            "export interface ProjectData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  name: string;\n"
            "  description: string;\n"
            "  status: ProjectStatus;\n"
            "}\n",
            "export interface OutboxStatusData {\n"
            "  pending: number;\n"
            "  processing: number;\n"
            "  retry: number;\n"
            "  processed: number;\n"
            "  dead_letter: number;\n"
            "  total: number;\n"
            "}\n",
            "export interface RecoveryStatusData {\n"
            '  status: "CLEAN" | "RECOVERY_REQUIRED";\n'
            "  pending: number;\n"
            "  retry: number;\n"
            "  dead_letter: number;\n"
            "  reconcile_required: number;\n"
            "  interrupted_jobs: number;\n"
            "}\n",
            "export interface RecoveryReconcileRequest {\n"
            "  project_id?: string | null;\n"
            "  limit?: number;\n"
            "}\n",
            "export interface RecoveryReconcileData {\n"
            "  reclaimed: number;\n"
            "  dispatched: Record<string, number>;\n"
            "  reconcile_required: number;\n"
            "  project: RecoveryStatusData | null;\n"
            "}\n",
            "export interface DomainRuleContribution {\n"
            "  rule_id: string;\n"
            "  rule_version: string;\n"
            "  phase: DomainRulePhase;\n"
            "  inputs: string[];\n"
            "  severity: IssueSeverity;\n"
            "  priority: number;\n"
            '  safety_mode: "ADDITIVE";\n'
            "}\n",
            "export interface DomainGeneratorContribution {\n"
            "  generator_id: string;\n"
            "  version: string;\n"
            "  consumes: string[];\n"
            "  produces: string[];\n"
            "  requires_capabilities: string[];\n"
            "  before: string[];\n"
            "  after: string[];\n"
            "  deterministic: boolean;\n"
            "  side_effects: boolean;\n"
            "}\n",
            "export interface DomainContextContribution {\n"
            "  context_id: string;\n"
            "  keys: string[];\n"
            "  description: string;\n"
            "}\n",
            "export interface DomainValidationDiagnostic {\n"
            "  rule_id: string;\n"
            '  status: "PASS" | "FAIL" | "UNKNOWN" | "BLOCKED";\n'
            "  message: string;\n"
            "  details: Record<string, unknown>;\n"
            "}\n",
            "export interface DomainValidationResult {\n"
            "  domain_id: string;\n"
            "  diagnostics: DomainValidationDiagnostic[];\n"
            "}\n",
            "export interface DomainUIContribution {\n"
            "  extension_id: string;\n"
            '  kind: "navigation" | "action" | "form";\n'
            "  label: string;\n"
            "  route: string;\n"
            "  json_schema: Record<string, unknown>;\n"
            "  action: string | null;\n"
            "}\n",
            "export interface DomainDescriptorData {\n"
            "  id: string;\n"
            "  plugin_id: string;\n"
            "  name: string;\n"
            "  version: string;\n"
            "  api_version: string;\n"
            "  schema_version: string;\n"
            "  trust_tier: DomainTrustTier;\n"
            "  entrypoint: string;\n"
            "  capabilities: string[];\n"
            "  required_capabilities: string[];\n"
            "  requires_domains: string[];\n"
            "  optional_domains: string[];\n"
            "  conflicts_with: string[];\n"
            "  priority: number;\n"
            "  rule_phases: DomainRulePhase[];\n"
            "  generator_phases: string[];\n"
            "  migration_provider: string | null;\n"
            "  context_contributions: string[];\n"
            "  ui_contributions: string[];\n"
            "  permissions: Permission[];\n"
            "}\n",
            "export interface DomainAvailableData {\n"
            "  descriptor: DomainDescriptorData;\n"
            "  active: boolean;\n"
            "}\n",
            "export interface DomainActivationData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string;\n"
            "  domain_id: string;\n"
            "  plugin_id: string;\n"
            "  plugin_version: string;\n"
            "  domain_schema_version: string;\n"
            "  configuration_schema_version: string;\n"
            "  configuration_schema_hash: string | null;\n"
            "  status: DomainActivationStatus;\n"
            "  configuration: Record<string, unknown>;\n"
            "  activated_at: string;\n"
            "  activated_by: string;\n"
            "  capability_snapshot: Record<string, unknown>;\n"
            "  dependency_snapshot: Record<string, unknown>;\n"
            "}\n",
            "export interface DomainCompositionData {\n"
            "  active_domain_ids: string[];\n"
            "  ordered_domain_ids: string[];\n"
            "  dependency_edges: string[][];\n"
            "  capability_routes: Record<string, string>;\n"
            "  rules: DomainRuleContribution[];\n"
            "  generators: DomainGeneratorContribution[];\n"
            "  context_contributions: DomainContextContribution[];\n"
            "  ui_contributions: DomainUIContribution[];\n"
            "  validation_results: DomainValidationResult[];\n"
            "}\n",
            "export interface DomainSchemaData {\n"
            "  domain_id: string;\n"
            "  schema_version: string;\n"
            "  json_schema: Record<string, unknown>;\n"
            "}\n",
            "export interface DomainActivationRequest {\n"
            "  configuration: Record<string, unknown> | null;\n"
            "  activated_by: string;\n"
            "}\n",
            "export interface DomainValidationRequest {\n"
            "  domain_ids: string[];\n"
            "  selected_capabilities: Record<string, string>;\n"
            "  domain_ir?: Record<string, unknown> | null;\n"
            "  mcu_config_id?: string | null;\n"
            "}\n",
            "export interface DocumentUploadRequest {\n"
            "  filename: string;\n"
            "  content_base64: string;\n"
            "  document_type: DocumentType;\n"
            "  vendor: string | null;\n"
            "  product: string | null;\n"
            "  version_label: string | null;\n"
            "}\n",
            "export interface DocumentData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string | null;\n"
            "  filename: string;\n"
            "  document_type: DocumentType;\n"
            "  vendor: string | null;\n"
            "  product: string | null;\n"
            "  version_label: string | null;\n"
            "  content_hash: string;\n"
            "  storage_uri: string;\n"
            "  parse_status: DocumentParseStatus;\n"
            "  parse_error: string | null;\n"
            "}\n",
            "export interface EvidenceCreateRequest {\n"
            "  evidence_type: EvidenceType;\n"
            "  locator: Record<string, unknown>;\n"
            "  source_uri: string | null;\n"
            "  content_hash: string | null;\n"
            "  summary: string;\n"
            "}\n",
            "export interface EvidenceData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string | null;\n"
            "  evidence_type: EvidenceType;\n"
            "  locator: Record<string, unknown>;\n"
            "  source_uri: string | null;\n"
            "  content_hash: string | null;\n"
            "  files: string[];\n"
            "  summary: string;\n"
            "}\n",
            "export interface CANTransportConfig {\n"
            "  nominal_bitrate: number;\n"
            "  frame_kind: string;\n"
            "  data_bitrate: number | null;\n"
            "  fd_brs: boolean | null;\n"
            "}\n",
            "export interface ProtocolTransport {\n"
            "  transport_id: string;\n"
            "  name: string;\n"
            "  transport_type: string;\n"
            "  can: CANTransportConfig;\n"
            "}\n",
            "export interface ProtocolField {\n"
            "  field_id: string;\n"
            "  name: string;\n"
            "  bit_offset: number;\n"
            "  bit_length: number;\n"
            "  endian: string;\n"
            "  signed: boolean;\n"
            "  scale: number;\n"
            "  offset: number;\n"
            "  unit: string;\n"
            "  minimum: number | null;\n"
            "  maximum: number | null;\n"
            "}\n",
            "export interface ProtocolMessage {\n"
            "  message_id: string;\n"
            "  name: string;\n"
            "  transport_ref: string;\n"
            "  can_id: number;\n"
            "  extended_id: boolean;\n"
            "  payload_length_bytes: number;\n"
            "  fields: ProtocolField[];\n"
            "  requirement_ids: string[];\n"
            "  description: string;\n"
            "}\n",
            "export interface ProtocolDefinition {\n"
            "  version_label: string;\n"
            "  transports: ProtocolTransport[];\n"
            "  messages: ProtocolMessage[];\n"
            "  requirement_ids: string[];\n"
            "  evidence_ids: string[];\n"
            "}\n",
            "export type ProtocolCreateRequest = ProtocolDefinition;\n",
            "export interface ProtocolIR extends ProtocolDefinition {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string;\n"
            "  input_hash: string;\n"
            "}\n",
            "export interface ProtocolUpdateRequest extends ProtocolDefinition {\n"
            "  expected_revision?: number | null;\n"
            "}\n",
            "export interface ProtocolValidationDiagnostic {\n"
            "  rule_id: string;\n"
            '  status: "PASS" | "FAIL" | "UNKNOWN" | "BLOCKED";\n'
            "  message: string;\n"
            "  details: Record<string, unknown>;\n"
            "}\n",
            "export interface ProtocolValidationResult {\n"
            "  protocol_id: string;\n"
            "  protocol_revision: number;\n"
            "  input_hash: string;\n"
            "  diagnostics: ProtocolValidationDiagnostic[];\n"
            "}\n",
            "export interface GeneratedProtocolOutput {\n"
            '  target: "C" | "PYTHON" | "DBC" | "MARKDOWN";\n'
            "  path: string;\n"
            "  content: string;\n"
            "  content_hash: string;\n"
            "  input_hash: string;\n"
            "  protocol_revision: number;\n"
            "  generator_version: string;\n"
            "}\n",
            "export interface ProtocolGenerationBundle {\n"
            "  protocol_id: string;\n"
            "  protocol_revision: number;\n"
            "  input_hash: string;\n"
            "  generator_version: string;\n"
            "  outputs: GeneratedProtocolOutput[];\n"
            "}\n",
            "export interface ProtocolValidateRequest {\n"
            "  protocol_id?: string | null;\n"
            "  revision?: number | null;\n"
            "}\n",
            "export interface ProtocolGenerateRequest {\n"
            "  protocol_id?: string | null;\n"
            "  revision?: number | null;\n"
            "}\n",
            "export interface TestCase {\n"
            "  id: string;\n"
            "  code: string;\n"
            "  title: string;\n"
            "  type: TestType;\n"
            "  requirement_ids: string[];\n"
            "  preconditions: string[];\n"
            "  setup: string[];\n"
            "  inputs: Record<string, unknown>;\n"
            "  steps: string[];\n"
            "  expected: string[];\n"
            "  timeout: string;\n"
            "  pass_condition: string;\n"
            "  cleanup: string[];\n"
            "  automation_level: AutomationLevel;\n"
            "  executor_id: string | null;\n"
            "  executor_config: Record<string, unknown>;\n"
            "  required: boolean;\n"
            "  evidence_ids: string[];\n"
            "}\n",
            "export interface TestIR {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string;\n"
            "  requirement_ids: string[];\n"
            "  cases: TestCase[];\n"
            "  input_hash: string;\n"
            "  generator_version: string;\n"
            "  policy_version: string;\n"
            "  evidence_ids: string[];\n"
            "}\n",
            "export interface TestCaseResult {\n"
            "  id: string;\n"
            "  test_case_id: string;\n"
            "  test_case_code: string;\n"
            "  status: TestExecutionStatus;\n"
            "  duration_ms: number;\n"
            "  message: string;\n"
            "  observed: unknown;\n"
            "  expected: unknown;\n"
            "  evidence_ids: string[];\n"
            "  executor_id: string | null;\n"
            "  failure: Record<string, unknown> | null;\n"
            "}\n",
            "export interface TestRun {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string;\n"
            "  test_ir_id: string;\n"
            "  test_ir_revision: number;\n"
            "  test_input_hash: string;\n"
            "  source_revision_id: string;\n"
            "  status: TestExecutionStatus;\n"
            "  started_at: string;\n"
            "  finished_at: string | null;\n"
            "  case_results: TestCaseResult[];\n"
            "  tool_versions: Record<string, string>;\n"
            "  evidence_ids: string[];\n"
            "}\n",
            "export interface TestGenerationData {\n"
            "  test_ir: TestIR;\n"
            "  coverage_gaps: string[];\n"
            "}\n",
            "export interface TestRunRequest {\n"
            "  test_ir_id?: string | null;\n"
            "  source_revision_id: string;\n"
            "}\n",
            "export interface CoverageData {\n"
            "  total_requirements: number;\n"
            "  release_critical_requirements: number;\n"
            "  covered_requirements: number;\n"
            "  verified_requirements: number;\n"
            "  design_coverage_ratio: number;\n"
            "  verification_coverage_ratio: number;\n"
            "  uncovered_requirement_ids: string[];\n"
            "  unexecuted_requirement_ids: string[];\n"
            "  failing_requirement_ids: string[];\n"
            "  blocked_requirement_ids: string[];\n"
            "  unknown_requirement_ids: string[];\n"
            "}\n",
            "export interface TraceabilityData {\n"
            "  edges: Record<string, unknown>[];\n"
            "  coverage: CoverageData;\n"
            "  orphan_tests: string[];\n"
            "  uncovered_requirements: string[];\n"
            "}\n",
            "export interface ReviewFinding {\n"
            "  code: string;\n"
            "  title: string;\n"
            "  message: string;\n"
            "  source_kind: string;\n"
            "  source_ref: string;\n"
            "  severity: IssueSeverity;\n"
            "  status: TestExecutionStatus;\n"
            "  affected_refs: string[];\n"
            "  evidence_ids: string[];\n"
            "  deterministic: boolean;\n"
            "  dedupe_key: string;\n"
            "}\n",
            "export interface ReviewRun {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string;\n"
            "  source_revision_id: string;\n"
            "  policy_version: string;\n"
            "  input_hash: string;\n"
            "  build_run_id: string | null;\n"
            "  static_analysis_id: string | null;\n"
            "  test_run_id: string | null;\n"
            "  test_ir_id: string | null;\n"
            "  test_ir_revision: number | null;\n"
            "  protocol_id: string | null;\n"
            "  protocol_revision: number | null;\n"
            "  status: TestExecutionStatus;\n"
            "  findings: ReviewFinding[];\n"
            "  issue_ids: string[];\n"
            "}\n",
            "export interface ReviewRequest {\n"
            "  source_revision_id: string;\n"
            "  test_ir_id?: string | null;\n"
            "  test_run_id?: string | null;\n"
            "  build_run_id?: string | null;\n"
            "  static_analysis_id?: string | null;\n"
            "  schematic_id?: string | null;\n"
            "  require_build?: boolean;\n"
            "  require_static_analysis?: boolean;\n"
            "  require_erc?: boolean;\n"
            "}\n",
            "export interface IssueData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string;\n"
            "  code: string;\n"
            "  title: string;\n"
            "  description: string;\n"
            "  severity: IssueSeverity;\n"
            "  status: IssueStatus;\n"
            "  claim_ids: string[];\n"
            "  evidence_ids: string[];\n"
            "  resolution: string | null;\n"
            "  dedupe_key: string | null;\n"
            "  source_kind: string | null;\n"
            "  source_ref: string | null;\n"
            "  affected_refs: string[];\n"
            "  first_seen_at: string | null;\n"
            "  last_seen_at: string | null;\n"
            "  occurrence_count: number;\n"
            "  last_review_id: string | null;\n"
            "}\n",
            "export interface IssueMutationRequest {\n"
            "  project_id: string;\n"
            "  reason: string;\n"
            "  expected_revision?: number | null;\n"
            "}\n",
        ]
    )
    return "\n".join(sections)
