"""Small deterministic TypeScript contract generator for Core API types."""

import json
from enum import StrEnum

from eea_core.enums import (
    ArtifactStatus,
    DecisionStatus,
    EngineeringErrorCode,
    EvidenceType,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    TraceabilityRelation,
)

CORE_ENUMS: tuple[type[StrEnum], ...] = (
    ArtifactStatus,
    DecisionStatus,
    EngineeringErrorCode,
    EvidenceType,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    TraceabilityRelation,
)


def _lower_camel(name: str) -> str:
    return name[0].lower() + name[1:]


def _render_enum(enum_type: type[StrEnum]) -> str:
    constant_name = f"{_lower_camel(enum_type.__name__)}Values"
    values = json.dumps([member.value for member in enum_type], indent=2)
    return (
        f"export const {constant_name} = {values} as const;\n"
        f"export type {enum_type.__name__} = (typeof {constant_name})[number];\n"
    )


def render_typescript_contract() -> str:
    sections = [
        "// Generated by `eea openapi typescript`; do not edit manually.\n",
        "export interface ApiEnvelope<T> {\n"
        "  success: true;\n"
        "  data: T;\n"
        "  request_id: string;\n"
        "}\n",
    ]
    sections.extend(_render_enum(enum_type) for enum_type in CORE_ENUMS)
    sections.extend(
        [
            "export interface ApiError {\n"
            "  code: EngineeringErrorCode;\n"
            "  message: string;\n"
            "  details: Record<string, unknown>;\n"
            "}\n",
            "export interface ProjectData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  name: string;\n"
            "  description: string;\n"
            "  status: ProjectStatus;\n"
            "}\n",
        ]
    )
    return "\n".join(sections)
