"""Small deterministic TypeScript contract generator for Core API types."""

import json
from enum import StrEnum

from eea_core.enums import (
    ArtifactStatus,
    ClaimConflictStatus,
    ClaimConflictStrategy,
    ClaimConflictType,
    ClaimLifecycle,
    DecisionStatus,
    DeviceCategory,
    DeviceMergeConflictType,
    DocumentParseStatus,
    DocumentType,
    DomainActivationStatus,
    DomainRulePhase,
    DomainTrustTier,
    EngineeringDimension,
    EngineeringErrorCode,
    EvidenceType,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    RequirementFieldStatus,
    RequirementPriority,
    RequirementStatus,
    RequirementType,
    RequirementValueType,
    StaticAnalysisStatus,
    TraceabilityRelation,
    VerificationLevel,
)

CORE_ENUMS: tuple[type[StrEnum], ...] = (
    ArtifactStatus,
    ClaimConflictStatus,
    ClaimConflictStrategy,
    ClaimConflictType,
    ClaimLifecycle,
    DecisionStatus,
    DomainActivationStatus,
    DomainRulePhase,
    DomainTrustTier,
    DeviceCategory,
    DeviceMergeConflictType,
    DocumentParseStatus,
    DocumentType,
    EngineeringDimension,
    EngineeringErrorCode,
    EvidenceType,
    IssueSeverity,
    IssueStatus,
    JobStatus,
    Permission,
    ProjectStatus,
    RequirementFieldStatus,
    RequirementPriority,
    RequirementStatus,
    RequirementType,
    RequirementValueType,
    StaticAnalysisStatus,
    TraceabilityRelation,
    VerificationLevel,
)


def _lower_camel(name: str) -> str:
    return name[0].lower() + name[1:]


def _render_enum(enum_type: type[StrEnum]) -> str:
    constant_name = f"{_lower_camel(enum_type.__name__)}Values"
    values = json.dumps([member.value for member in enum_type], indent=2)
    return (
        f"export const {constant_name} = {values} as const;\n"
        f"export type {enum_type.__name__} = (typeof {constant_name})[number];\n"
    )


def render_typescript_contract() -> str:
    sections = [
        "// Generated by `eea openapi typescript`; do not edit manually.\n",
        "export interface ApiEnvelope<T> {\n"
        "  success: true;\n"
        "  data: T;\n"
        "  request_id: string;\n"
        "}\n",
    ]
    sections.extend(_render_enum(enum_type) for enum_type in CORE_ENUMS)
    sections.extend(
        [
            "export interface ApiError {\n"
            "  code: EngineeringErrorCode;\n"
            "  message: string;\n"
            "  details: Record<string, unknown>;\n"
            "}\n",
            "export interface ProjectData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  name: string;\n"
            "  description: string;\n"
            "  status: ProjectStatus;\n"
            "}\n",
            "export interface DomainRuleContribution {\n"
            "  rule_id: string;\n"
            "  rule_version: string;\n"
            "  phase: DomainRulePhase;\n"
            "  inputs: string[];\n"
            "  severity: IssueSeverity;\n"
            "  priority: number;\n"
            '  safety_mode: "ADDITIVE";\n'
            "}\n",
            "export interface DomainGeneratorContribution {\n"
            "  generator_id: string;\n"
            "  version: string;\n"
            "  consumes: string[];\n"
            "  produces: string[];\n"
            "  requires_capabilities: string[];\n"
            "  before: string[];\n"
            "  after: string[];\n"
            "  deterministic: boolean;\n"
            "  side_effects: boolean;\n"
            "}\n",
            "export interface DomainContextContribution {\n"
            "  context_id: string;\n"
            "  keys: string[];\n"
            "  description: string;\n"
            "}\n",
            "export interface DomainUIContribution {\n"
            "  extension_id: string;\n"
            '  kind: "navigation" | "action" | "form";\n'
            "  label: string;\n"
            "  route: string;\n"
            "  json_schema: Record<string, unknown>;\n"
            "  action: string | null;\n"
            "}\n",
            "export interface DomainDescriptorData {\n"
            "  id: string;\n"
            "  plugin_id: string;\n"
            "  name: string;\n"
            "  version: string;\n"
            "  api_version: string;\n"
            "  schema_version: string;\n"
            "  trust_tier: DomainTrustTier;\n"
            "  entrypoint: string;\n"
            "  capabilities: string[];\n"
            "  required_capabilities: string[];\n"
            "  requires_domains: string[];\n"
            "  optional_domains: string[];\n"
            "  conflicts_with: string[];\n"
            "  priority: number;\n"
            "  rule_phases: DomainRulePhase[];\n"
            "  generator_phases: string[];\n"
            "  migration_provider: string | null;\n"
            "  context_contributions: string[];\n"
            "  ui_contributions: string[];\n"
            "  permissions: Permission[];\n"
            "}\n",
            "export interface DomainAvailableData {\n"
            "  descriptor: DomainDescriptorData;\n"
            "  active: boolean;\n"
            "}\n",
            "export interface DomainActivationData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string;\n"
            "  domain_id: string;\n"
            "  plugin_id: string;\n"
            "  plugin_version: string;\n"
            "  domain_schema_version: string;\n"
            "  status: DomainActivationStatus;\n"
            "  configuration: Record<string, unknown>;\n"
            "  activated_at: string;\n"
            "  activated_by: string;\n"
            "  capability_snapshot: Record<string, unknown>;\n"
            "  dependency_snapshot: Record<string, unknown>;\n"
            "}\n",
            "export interface DomainCompositionData {\n"
            "  active_domain_ids: string[];\n"
            "  ordered_domain_ids: string[];\n"
            "  dependency_edges: string[][];\n"
            "  capability_routes: Record<string, string>;\n"
            "  rules: DomainRuleContribution[];\n"
            "  generators: DomainGeneratorContribution[];\n"
            "  context_contributions: DomainContextContribution[];\n"
            "  ui_contributions: DomainUIContribution[];\n"
            "}\n",
            "export interface DomainSchemaData {\n"
            "  domain_id: string;\n"
            "  schema_version: string;\n"
            "  json_schema: Record<string, unknown>;\n"
            "}\n",
            "export interface DomainActivationRequest {\n"
            "  configuration: Record<string, unknown>;\n"
            "  activated_by: string;\n"
            "}\n",
            "export interface DomainValidationRequest {\n"
            "  domain_ids: string[];\n"
            "  selected_capabilities: Record<string, string>;\n"
            "}\n",
            "export interface DocumentUploadRequest {\n"
            "  filename: string;\n"
            "  content_base64: string;\n"
            "  document_type: DocumentType;\n"
            "  vendor: string | null;\n"
            "  product: string | null;\n"
            "  version_label: string | null;\n"
            "}\n",
            "export interface DocumentData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string | null;\n"
            "  filename: string;\n"
            "  document_type: DocumentType;\n"
            "  vendor: string | null;\n"
            "  product: string | null;\n"
            "  version_label: string | null;\n"
            "  content_hash: string;\n"
            "  storage_uri: string;\n"
            "  parse_status: DocumentParseStatus;\n"
            "  parse_error: string | null;\n"
            "}\n",
            "export interface EvidenceCreateRequest {\n"
            "  evidence_type: EvidenceType;\n"
            "  locator: Record<string, unknown>;\n"
            "  source_uri: string | null;\n"
            "  content_hash: string | null;\n"
            "  summary: string;\n"
            "}\n",
            "export interface EvidenceData {\n"
            "  id: string;\n"
            "  schema_version: string;\n"
            "  revision: number;\n"
            "  created_at: string;\n"
            "  updated_at: string;\n"
            "  metadata: Record<string, unknown>;\n"
            "  project_id: string | null;\n"
            "  evidence_type: EvidenceType;\n"
            "  locator: Record<string, unknown>;\n"
            "  source_uri: string | null;\n"
            "  content_hash: string | null;\n"
            "  files: string[];\n"
            "  summary: string;\n"
            "}\n",
        ]
    )
    return "\n".join(sections)
