"""Bounded hardware commissioning port contracts."""

from typing import Protocol


class HardwareCommissioningPort(Protocol):
    """Only bounded safety operations may cross the application/adapter boundary."""

    name: str
    version: str

    def identify_target(self) -> object: ...

    def verify_probe(self, expected: object) -> object: ...

    def flash(self, firmware_hash: str) -> object: ...

    def verify_flash(self, firmware_hash: str) -> object: ...

    def reset_to_safe_state(self) -> object: ...

    def enter_safe_state(self) -> object: ...

    def read_fault_state(self) -> object: ...

    def sensor_sanity_check(self) -> object: ...

    def watchdog_status(self) -> object: ...

    def emergency_stop(self) -> object: ...

    def execute_limited_step(self, step_id: str, limits: object) -> object: ...


__all__ = ["HardwareCommissioningPort"]
